export {
  applyMask,
  BrushDeviceUnavailableError,
  BrushMaskCapabilityUnavailableError,
  createBrushStroke,
  createEraseBrushStroke,
  createRevealBrushStroke,
  deleteMask,
  disableMask,
  duplicateMask,
  invertMask,
  normalizeBrushConfig,
  setMaskDisplayMode,
  transformMask,
  type BrushMaskControl,
  type BrushMaskControlOperation,
  type BrushMaskTransform,
  type BrushConfig,
  type BrushMode,
  type BrushStroke,
  type PointerSample,
} from "./types";
