[settings.proxy]
enable = true

[daemons.app]
run = "./node_modules/.bin/vite --host 127.0.0.1 --port $PORT --strictPort"
dir = "."
port = { expect = [1420], bump = 20 }
ready_port = { port = 1420, timeout = "30s" }

[daemons.docs]
run = "./node_modules/.bin/vitepress dev . --host 127.0.0.1 --port $PORT --strictPort"
dir = "packages/docs"
port = { expect = [5173], bump = 20 }
ready_port = { port = 5173, timeout = "30s" }
